In [4]:
import os
import pandas as pd

df = pd.read_excel('data/NaverFinance.xlsx')
df.head(5)

,Unnamed: 0,종목명,현재가,전일비,등락률,액면가,거래량,거래대금,전일거래량,시가,...,주당순이익,보통주배당금,매출액증가율,영업이익증가율,외국인비율,PER,ROE,ROA,PBR,유보율
0,0,삼성전자,"71,000",500,+0.71%,100,"12,330,251","874,607","11,688,599","71,100",...,"5,240","1,444",8.09,-15.99,53.29,13.55,17.07,12.72,1.38,"38,144.3"
1,1,LG에너지솔루션,"495,000","4,500",-0.90%,500,"205,029","101,498","300,881","491,000",...,"5,895",NaN,43.39,57.94,5.10,83.97,5.75,2.51,5.78,"15,657.4"
2,2,SK하이닉스,"119,700","3,000",+2.57%,"5,000","2,904,321","345,843","2,749,688","117,900",...,"-11,253","1,200",3.78,-45.13,52.26,-10.64,3.56,2.24,1.43,"1,668.3"
3,3,삼성바이오로직스,"722,000","1,000",-0.14%,"2,500","21,871","15,807","35,310","720,000",...,"11,601",NaN,91.41,83.07,10.37,62.24,11.42,6.50,5.52,"4,950.5"
4,4,삼성전자우,"57,300",100,+0.17%,100,"809,067","46,371","893,637","57,300",...,"5,240",NaN,NaN,NaN,72.57,10.94,NaN,NaN,1.12,NaN

In [5]:
#모든 숫자를 실수로 변경
for col in df.columns:
    if col != '종목명' and df[col].dtype == 'O': 
        df[col] = df[col].str.replace(',', '').str.replace('%', '').astype(float).copy()

df.head(5)

,Unnamed: 0,종목명,현재가,전일비,등락률,액면가,거래량,거래대금,전일거래량,시가,...,주당순이익,보통주배당금,매출액증가율,영업이익증가율,외국인비율,PER,ROE,ROA,PBR,유보율
0,0,삼성전자,71000.0,500.0,0.71,100.0,12330251.0,874607.0,11688599.0,71100.0,...,5240.0,1444.0,8.09,-15.99,53.29,13.55,17.07,12.72,1.38,38144.3
1,1,LG에너지솔루션,495000.0,4500.0,-0.90,500.0,205029.0,101498.0,300881.0,491000.0,...,5895.0,NaN,43.39,57.94,5.10,83.97,5.75,2.51,5.78,15657.4
2,2,SK하이닉스,119700.0,3000.0,2.57,5000.0,2904321.0,345843.0,2749688.0,117900.0,...,-11253.0,1200.0,3.78,-45.13,52.26,-10.64,3.56,2.24,1.43,1668.3
3,3,삼성바이오로직스,722000.0,1000.0,-0.14,2500.0,21871.0,15807.0,35310.0,720000.0,...,11601.0,NaN,91.41,83.07,10.37,62.24,11.42,6.50,5.52,4950.5
4,4,삼성전자우,57300.0,100.0,0.17,100.0,809067.0,46371.0,893637.0,57300.0,...,5240.0,NaN,NaN,NaN,72.57,10.94,NaN,NaN,1.12,NaN

In [6]:
#NaN 열 버리기
df_dropna = df.dropna(subset=['시가총액', 'PER', 'PBR', '매출액'])

df_dropna.head()

,Unnamed: 0,종목명,현재가,전일비,등락률,액면가,거래량,거래대금,전일거래량,시가,...,주당순이익,보통주배당금,매출액증가율,영업이익증가율,외국인비율,PER,ROE,ROA,PBR,유보율
0,0,삼성전자,71000.0,500.0,0.71,100.0,12330251.0,874607.0,11688599.0,71100.0,...,5240.0,1444.0,8.09,-15.99,53.29,13.55,17.07,12.72,1.38,38144.3
1,1,LG에너지솔루션,495000.0,4500.0,-0.90,500.0,205029.0,101498.0,300881.0,491000.0,...,5895.0,NaN,43.39,57.94,5.10,83.97,5.75,2.51,5.78,15657.4
2,2,SK하이닉스,119700.0,3000.0,2.57,5000.0,2904321.0,345843.0,2749688.0,117900.0,...,-11253.0,1200.0,3.78,-45.13,52.26,-10.64,3.56,2.24,1.43,1668.3
3,3,삼성바이오로직스,722000.0,1000.0,-0.14,2500.0,21871.0,15807.0,35310.0,720000.0,...,11601.0,NaN,91.41,83.07,10.37,62.24,11.42,6.50,5.52,4950.5
5,5,POSCO홀딩스,532000.0,14000.0,-2.56,5000.0,919880.0,495685.0,1333031.0,539000.0,...,14836.0,12000.0,11.03,-47.50,28.76,35.86,6.11,3.75,0.74,11269.8

In [7]:
# 조건 1
wooryang_stocks = df_dropna[
    (df_dropna['시가총액'] >= 1000) &
    (df_dropna['매출액'] >= 100) &
    (df_dropna['PER'] >= 0) &
    (df_dropna['PBR'] <= 2)
]

# PBR 역수
wooryang_stocks['PBR_inverse'] = 1 / wooryang_stocks['PBR']

# PBR 역수 첫 100

top_100_stocks = wooryang_stocks.sort_values(by='PBR_inverse', ascending=False).head(100)

top_100_stocks[['종목명', '시가총액', '매출액', 'PER', 'PBR','PBR_inverse']].head()

/var/folders/sb/2gzn9_qx589_ft0jp8q6nbbc0000gn/T/ipykernel_3036/181713201.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wooryang_stocks['PBR_inverse'] = 1 / wooryang_stocks['PBR']

        종목명    시가총액      매출액   PER   PBR  PBR_inverse
289    태광산업  6502.0  27039.0  1.97  0.12     8.333333
414     HDC  3728.0  50449.0  6.78  0.13     7.692308
618    흥국화재  1953.0  45289.0  0.82  0.14     7.142857
441  티와이홀딩스  3359.0   3536.0  5.31  0.16     6.250000
759    대한화섬  1348.0   1509.0  4.64  0.16     6.250000

In [8]:
#우량주의 조건 2
rising_stocks = top_100_stocks[
    (top_100_stocks['거래량'] >= 0.01 * top_100_stocks['상장주식수']) &
    (top_100_stocks['등락률'] >= 0) &
    (top_100_stocks['현재가'] > top_100_stocks['시가'])
]

# 고가와 현재가의 차
rising_stocks['고가-현재가'] = (rising_stocks['고가'] - rising_stocks['현재가'])

# 고가-현재가의 차이가 적은 첫 10개
top_10_stocks_near_high = rising_stocks.sort_values(by='고가-현재가').head(10)

top_10_stocks_near_high[['종목명', '현재가', '시가', '고가', '등락률', '거래량', '상장주식수','고가-현재가','매출액']].head(10)

/var/folders/sb/2gzn9_qx589_ft0jp8q6nbbc0000gn/T/ipykernel_3036/1730772037.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rising_stocks['고가-현재가'] = (rising_stocks['고가'] - rising_stocks['현재가'])

,종목명,현재가,시가,고가,등락률,거래량,상장주식수,고가-현재가,매출액
127,한국가스공사,24700.0,24250.0,24700.0,2.07,235241.0,92313.0,0.0,517243.0
551,동양,1013.0,1009.0,1016.0,0.30,107482.0,238684.0,3.0,7677.0
446,교보증권,5070.0,5030.0,5080.0,0.80,15520.0,64653.0,10.0,40659.0
815,한솔홀딩스,2815.0,2800.0,2825.0,0.00,12613.0,42009.0,10.0,4672.0
285,HDC현대산업개발,10190.0,10070.0,10200.0,0.69,77542.0,65907.0,10.0,32983.0
547,현대지에프홀딩스,3825.0,3790.0,3845.0,0.92,108066.0,63824.0,20.0,39232.0
386,LF,14070.0,14000.0,14090.0,0.50,7337.0,29240.0,20.0,19685.0
128,BNK금융지주,6960.0,6870.0,6980.0,0.72,498716.0,322088.0,20.0,75756.0
2428,해성산업,8000.0,7940.0,8030.0,0.25,25901.0,32557.0,30.0,25316.0
431,한일홀딩스,11130.0,11100.0,11160.0,0.00,9944.0,30833.0,30.0,19656.0

In [2]:
import os
import pandas as pd

#절대경로는 여기
dir = '절대경로'
try:
    df = pd.read_excel('data/NaverFinance.xlsx')
except:
    df = pd.read_excel(dir)


# 불필요한 column 을 없앤다. 
remove = ['액면가', '거래대금', '외국인비율','매수호가', '매도호가','보통주배당금']
df_cleaned = df.drop(columns=remove)

df_cleaned.head()



#모든 숫자를 실수로 변경
for col in df.columns:
    if col != '종목명' and df[col].dtype == 'O': 
        df[col] = df[col].str.replace(',', '').str.replace('%', '').astype(float).copy()

#NaN 열 버리기
df_dropna = df.dropna(subset=['시가총액', 'PER', 'PBR', '매출액'])

# 조건 1
wooryang_stocks = df_dropna[
    (df_dropna['시가총액'] >= 1000) &
    (df_dropna['매출액'] >= 1) &
    (df_dropna['PER'] >= 0) &
    (df_dropna['PBR'] <= 2)
]

# PBR 역수
wooryang_stocks['PBR_inverse'] = 1 / wooryang_stocks['PBR']

# PBR 역수 첫 100
top_100_stocks = wooryang_stocks.sort_values(by='PBR_inverse', ascending=False).head(100)
#문제 2 
print('#### 문제 2 ####')
print(top_100_stocks[['종목명', 'PBR']].head(100).to_string(index=False))
top_100_stocks[['종목명', '시가총액', '매출액', 'PER', 'PBR','PBR_inverse']].head()


#우량주의 조건 2
rising_stocks = top_100_stocks[
    (top_100_stocks['거래량'] >= top_100_stocks['상장주식수'] * 1000/100) &
    (top_100_stocks['등락률'] >= 0) &
    (top_100_stocks['현재가'] > top_100_stocks['시가'])
]

# 고가 근처에 있는 주식 10개
rising_stocks['고가-현재가'] = (rising_stocks['고가'] - rising_stocks['현재가'])

# 고가-현재가의 차이가 적은 첫 10개
top_10_stocks_near_high = rising_stocks.sort_values(by='고가-현재가').head(10)

top_10_stocks_near_high[['종목명', '현재가', '시가', '고가', '등락률', '거래량', '상장주식수','고가-현재가']].head(10)

print("#### 문제 3 ####")
print(top_10_stocks_near_high['종목명'].tolist())

#### 문제 2 ####
      종목명  PBR
     태광산업 0.12
      HDC 0.13
     흥국화재 0.14
   티와이홀딩스 0.16
     대한화섬 0.16
 현대지에프홀딩스 0.16
     한화생명 0.16
      이마트 0.17
     계룡건설 0.17
   DB금융투자 0.18
     태영건설 0.19
   티케이케미칼 0.19
    세아홀딩스 0.19
       넥센 0.19
   한국가스공사 0.20
   한화손해보험 0.20
     교보증권 0.20
  세이브존I&C 0.20
    한솔홀딩스 0.21
   미래에셋생명 0.21
   KPX홀딩스 0.21
       한진 0.21
   SNT홀딩스 0.21
      BGF 0.21
       한화 0.22
    KCC건설 0.22
     동양생명 0.22
       E1 0.22
  DGB금융지주 0.22
     일신방직 0.23
    원익홀딩스 0.23
  BNK금융지주 0.23
    한일홀딩스 0.23
HDC현대산업개발 0.23
     대한제분 0.23
 KISCO홀딩스 0.23
   강남제비스코 0.24
       영풍 0.24
       동양 0.24
      삼천리 0.24
     서울가스 0.24
 골프존뉴딘홀딩스 0.24
     하림지주 0.24
       세방 0.25
    현대홈쇼핑 0.25
     화성산업 0.25
      코오롱 0.25
       서한 0.25
   피에이치에이 0.25
     유진기업 0.25
    현대차증권 0.26
     롯데지주 0.26
     현대제철 0.26
 한진중공업홀딩스 0.26
     대원산업 0.26
     한양증권 0.26
     부국증권 0.26
     기업은행 0.27
    농심홀딩스 0.27
     DL건설 0.27
       LF 0.27
     삼보판지 0.27
   한국앤컴퍼니 0.27
  SK디스커버리 0.27
       서연 0.27
     신도리코 0.28
     한국철강 0.28
   예스코홀딩스 0.28
      케이씨 0.28
     동원개발 0.29
   우리금융지주 0.29
 이베스트투자증권 0.29
     신영증권 0.29
   경동도시가스 0.29
      휴스틸 0.29
       무학 0.29
       선광 0.30
     동일산업 0.30
    DL이앤씨 0.30
      GRT 0.30
     해성산업 0.30
    매일홀딩스 0.30
    삼양홀딩스 0.30
    DRB동일 0.30
      아세아 0.30
       GS 0.30
    광주신세계 0.30
     삼성생명 0.31
       한섬 0.31
     미창석유 0.31
   하나금융지주 0.31
    현대백화점 0.31
     고려제강 0.31
    무림P&P 0.31
     현대해상 0.31
     삼영전자 0.31
    노루홀딩스 0.32
     다우기술 0.32
       코텍 0.32
     대한제강 0.32
#### 문제 3 ####
['노루홀딩스']

/var/folders/sb/2gzn9_qx589_ft0jp8q6nbbc0000gn/T/ipykernel_9984/2887219655.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wooryang_stocks['PBR_inverse'] = 1 / wooryang_stocks['PBR']
/var/folders/sb/2gzn9_qx589_ft0jp8q6nbbc0000gn/T/ipykernel_9984/2887219655.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rising_stocks['고가-현재가'] = (rising_stocks['고가'] - rising_stocks['현재가'])

In [18]:
import pandas as pd

finance=pd.read_excel("data/NaverFinance.xlsx", na_values=["N/A", "NA"], thousands=',')
df=finance.copy()

#####################1번#####################
print(f"{df.drop(['액면가', '거래대금', '매수호가', '매도호가', '외국인비율', 'Unnamed: 0'], axis=1).columns.values} \n")
#####################2번#####################
df.dropna(subset=['시가총액', '매출액', 'PER', 'PBR'], inplace=True)
df[['시가총액', '매출액', 'PER', 'PBR']] = df[['시가총액', '매출액', 'PER', 'PBR']].apply(pd.to_numeric, errors='coerce')
filtered_top_100_pbr = df[(df['시가총액'] >= 1000) & (df['매출액'] >= 1) & (df['PER'] >= 0) & (df['PBR'] <= 2)].copy()
filtered_top_100_pbr['PBR_inverse'] = 1 / filtered_top_100_pbr['PBR']
top_100_pbr = filtered_top_100_pbr.nlargest(100, 'PBR')
print(f"{top_100_pbr['종목명'].values} \n")
#####################3번#####################
df['등락률'] = df['등락률'].str.replace('%', '').astype(float) / 100
df.dropna(subset=['등락률', '거래량', '상장주식수', '현재가', '시가'], inplace=True)
selected_stocks = df[(df['거래량'] >= (df['상장주식수'] * 10)) & (df['등락률'] >= 0) & (df['현재가'] > df['시가'])].nlargest(10, '고가')
print(selected_stocks['종목명'].values)

['종목명' '현재가' '전일비' '등락률' '거래량' '전일거래량' '시가' '고가' '저가' '매수총잔량' '매도총잔량'
 '상장주식수' '시가총액' '매출액' '자산총계' '부채총계' '영업이익' '당기순이익' '주당순이익' '보통주배당금'
 '매출액증가율' '영업이익증가율' 'PER' 'ROE' 'ROA' 'PBR' '유보율']

['현대로템' '피에스케이홀딩스' '노바텍' '조이시티' '카카오뱅크' 'CMG제약' '엑셈' '케이엔솔' '미스터블루'
 '제이아이테크' '카카오' '월덱스' '엠투아이' '지아이텍' 'SFA반도체' '알서포트' '대아티아이' '인카금융서비스'
 '제이브이엠' '신스틸' '삼성엔지니어링' '세진중공업' '텔레칩스' '세아메카닉스' '쌍용C&E' '덕양산업' '바이브컴퍼니'
 'SK오션플랜트' '더블유씨피' '이브이첨단소재' '모델솔루션' '한온시스템' 'HB솔루션' '와이팜' '코미코'
 '시너지이노베이션' '영화테크' 'LIG넥스원' '휴젤' '티에스이' '상아프론테크' '유니테스트' '와이씨켐' '네오위즈'
 '이큐셀' '아모레퍼시픽' '디아이씨' '오리온' '대웅제약' '원익IPS' '원익QnC' '새로닉스' '범한퓨얼셀'
 'SM C&C' '에스코넥' '휴비츠' '뉴프렉스' '이수화학' '대한전선' 'KIB플러그에너지' '애니플러스' '대덕전자'
 '갤럭시아머니트리' '미원에스씨' '휴온스' '금양그린파워' '랩지노믹스' 'NICE평가정보' '코스메카코리아'
 'LS ELECTRIC' '에프에스티' '에코마케팅' '에치에프알' '브랜드엑스코퍼레이션' '네패스' '이녹스첨단소재'
 '에스퓨얼셀' '인성정보' '한화에어로스페이스' '피에스케이' '오리엔탈정공' '이원컴포텍' '효성중공업' '한솔아이원스' '상보'
 '종근당' '한양디지텍' '희림' '백광산업' 'NHN KCP' '제일기획' '프로텍' '삼화콘덴서' '상신이디피' '에스트래픽'
 '엔씨소프트' '제로투세븐' 'KG모빌리티' 'STX중공업' '대호에이엘']

['한미반도체' '코스모신소재' '코스모화학' '삼부토건' 'KG케미칼' 'SBS' '유니드' '서연이화' '화신' '남해화학'
 '대원강업' '삼진제약' '대한제당' '도화엔지니어링' '한미글로벌' 'AJ네트웍스' '경농' '경동인베스트' '한국무브넥스'
 '한국화장품' '인지컨트롤스' '노루홀딩스' '동성제약' '샘표' '샘표식품' '팜젠사이언스' '유니드비티플러스' '덕성'
 '유니온' '동원금속' '신송홀딩스' '조비' 'SJM' 'KR모터스' '신풍' 'JYP Ent.' '루닛' '주성엔지니어링'
 '차바이오텍' '에코프로에이치엔' '심텍' '아프리카TV' '네오위즈' '유진테크' '펩트론' '큐렉소' '성우하이텍'
 '셀바스AI' '지아이이노베이션' '브이티' '바텍' '네이처셀' '제이엘케이' '인탑스' 'KG ETS' '동운아나텍'
 '모트렉스' '엑세스바이오' '랩지노믹스' '제우스' '비올' '글로벌텍스프리' '시너지이노베이션' '에치에프알' '예스티'
 '양지사' '에스와이' '펨트론' '필옵틱스' '신테카바이오' '지앤비에스 에코' '스맥' '인벤티지랩' '영풍정밀'
 'SAMG엔터' '한양디지텍' '한일사료' '테라사이언스' '이지홀딩스' '드림시큐리티' '소룩스' '제이씨케미칼' '와이지-원'
 '차백신연구소' '모베이스전자' '에브리봇' '에이팩트' '아진산업' '에코플라스틱' '코리아나' '코닉오토메이션'
 '이노시뮬레이션' '엠투아이' '삼보모터스' '센서뷰' '드림씨아이에스' '버넥트' '디에이테크놀로지' 'SBS콘텐츠허브'
 '제이스코홀딩스' '꿈비' '희림' '오르비텍' '아가방컴퍼니' '빅솔론' '유신' '머큐리' '애니젠' '모바일어플라이언스'
 '미래생명자원' '이랜시스' 'FSN' '유니트론텍' '에코바이오' '덕신하우징' '라이콤' '액토즈소프트' '토마토시스템'
 '한주라이트메탈' '코리아에프티' 'NE능률' '현우산업' '삼기이브이' '보라티알' '인산가' '마이크로컨텍솔' '비투엔'
 '컬러레이' '지엔씨에너지' '네오크레마' '누보' '일지테크' '스튜디오산타클로스' '효성오앤비' '바이온' '아이엠'
 '마니커에프앤지' '아이즈비전' '디딤이앤에프' 'KB오토시스' '라닉스' '삼진' '지더블유바이텍' '케이바이오' '엔피디'
 '애드바이오텍' '리노스' '티피씨글로벌' '국일신동' 'THE MIDONG' '텔레필드' '누리플랜' '에이치엠씨제5호스팩']

In [16]:
df

,Unnamed: 0,종목명,현재가,전일비,등락률,액면가,거래량,거래대금,전일거래량,시가,...,주당순이익,보통주배당금,매출액증가율,영업이익증가율,외국인비율,PER,ROE,ROA,PBR,유보율
0,0,삼성전자,71000,500,0.0071,100,12330251,874607,11688599,71100,...,5240.0,1444.0,8.09,-15.99,53.29,13.55,17.07,12.72,1.38,38144.3
1,1,LG에너지솔루션,495000,4500,-0.0090,500,205029,101498,300881,491000,...,5895.0,NaN,43.39,57.94,5.10,83.97,5.75,2.51,5.78,15657.4
2,2,SK하이닉스,119700,3000,0.0257,5000,2904321,345843,2749688,117900,...,-11253.0,1200.0,3.78,-45.13,52.26,-10.64,3.56,2.24,1.43,1668.3
3,3,삼성바이오로직스,722000,1000,-0.0014,2500,21871,15807,35310,720000,...,11601.0,NaN,91.41,83.07,10.37,62.24,11.42,6.50,5.52,4950.5
5,5,POSCO홀딩스,532000,14000,-0.0256,5000,919880,495685,1333031,539000,...,14836.0,12000.0,11.03,-47.50,28.76,35.86,6.11,3.75,0.74,11269.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3757,3757,유진스팩9호,2400,95,-0.0381,100,55860,137,61730,2495,...,-4.0,NaN,NaN,NaN,0.34,-600.00,NaN,NaN,1.20,1866.4
3758,3758,신한제10호스팩,2220,0,0.0000,100,7818,17,7166,2220,...,22.0,NaN,NaN,NaN,0.08,100.91,NaN,NaN,1.17,1787.5
3759,3759,유진스팩6호,2520,0,0.0000,100,0,0,0,0,...,27.0,0.0,NaN,-68.55,0.48,93.33,0.45,0.38,1.30,1823.1
3760,3760,키움제6호스팩,2170,10,-0.0046,100,1325,3,6484,2180,...,8.0,NaN,NaN,-510.95,0.09,271.25,0.24,0.18,1.13,1822.4
3761,3761,엔에이치스팩25호,2460,0,0.0000,100,0,0,0,0,...,24.0,0.0,NaN,NaN,0.29,102.50,NaN,NaN,1.33,1729.9

In [40]:
import pandas as pd

base_stock_data=pd.read_excel('data/NaverFinance.xlsx', sheet_name='Sheet1', thousands = ',')

# 1. 불필요한 컬럼을 없앤다
# (액면가, 거래대금, 매수호가, 매도호가, 외국인 비율 등등)
def getTrimData(base_stock_data) :
    trim_data = base_stock_data[['종목명','거래량','상장주식수','등락률','현재가','시가','고가','PER','시가총액','매출액','PBR']]
    return trim_data

# 2. 우량한 주식을 선정한다.
# 시가총액 1000억 이상, 매출액 1억 이상, per 0 이상, pbr 2이하
# 이들 중 Null인 값이 하나라도 있으면 해당 주식은 제외
# PBR의 역수가 큰 순서대로 100개의 주식을 우량주식으로 선정함.
def getBlueChip100(trim_data):
    trim_data = trim_data.loc[trim_data['시가총액'].notna() & trim_data['매출액'].notna()& trim_data['PER'].notna()& trim_data['PBR'].notna()]
    trim_data = trim_data.loc[
        (trim_data['시가총액'] >= 1000) & 
        (trim_data['매출액'] >= 1) & 
        (trim_data['PER'] >= 0) & 
        (trim_data['PBR'] <= 2)]
    
    trim_data['reciprocal_of_PBR'] = 1/trim_data['PBR']
    
    blue_chip = trim_data.sort_values(by='reciprocal_of_PBR', ascending=False ).head(100)
    return blue_chip

# 3. 우량주 중 오르고 있는 주식을 선정한다.
# 상장주식수의 1% 이상 거래량, 전일 대비 등락률 0%이상, 현재가가 시가보다 높은 주식 중에서 고가 근처에 있는 주식 10개를 선정.
def getTop10(blue_chip):
    blue_chip = blue_chip.loc[(blue_chip['거래량'] >= blue_chip['상장주식수']*1000/100) & (blue_chip['등락률'].str[0] != '-') & (blue_chip['현재가'] > blue_chip['시가'])]
    # 고가 근처에 있는 주식을 10개 선정
    # 근처 → 고가를 1로 가정했을 때 종가가 1에 가장 가까운 주식을 확인
    # ex) 주식1 : 고가2 종가1
    #     주식2 : 고가3 종가2
    #     2가 고가에 더 가깝다고 판정
    #     → 종가/고가가 높을수록 가깝다고 판정
    blue_chip = blue_chip.loc[blue_chip['현재가'] > blue_chip['시가']]
    blue_chip['closing_price_percentage'] = blue_chip['현재가']/blue_chip['고가']
    top10 = blue_chip.sort_values(by='closing_price_percentage', ascending=False).head(10)
    return top10



print("불필요한 컬럼을 제거")
trimData = getTrimData(base_stock_data)
print(trimData.columns)
print(trimData)
print("ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ")
print("선정된 우량주식100")
blue_chip = getBlueChip100(trimData)
print(blue_chip)
print("ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ")
print("우량주식 중 오르고 있는 주식 10개 선정")
top10 = getTop10(blue_chip)
print(top10)

불필요한 컬럼을 제거
Index(['종목명', '거래량', '상장주식수', '등락률', '현재가', '시가', '고가', 'PER', '시가총액', '매출액',
       'PBR'],
      dtype='object')
               종목명       거래량    상장주식수     등락률     현재가      시가      고가  \
0             삼성전자  12330251  5969783  +0.71%   71000   71100   71600
1         LG에너지솔루션    205029   234000  -0.90%  495000  491000  502000
2           SK하이닉스   2904321   728002  +2.57%  119700  117900  120700
3         삼성바이오로직스     21871    71174  -0.14%  722000  720000  729000
4            삼성전자우    809067   822887  +0.17%   57300   57300   57500
...            ...       ...      ...     ...     ...     ...     ...
3760       키움제6호스팩      1325     3430  -0.46%    2170    2180    2180
3761     엔에이치스팩25호         0     3020   0.00%    2460       0       0
3762  에스케이증권제10호스팩     33308     3310  -0.47%    2110    2105    2115
3763         소프트센우       382      357  -0.10%    9750    9760    9760
3764        대호특수강우        68      424  -1.34%    8120    8110    8220

          PER     시가총액        매출액    PBR
0       13.55  4238546  3022314.0   1.38
1       83.97  1158300   255986.0   5.78
2      -10.64   871419   446216.0   1.43
3       62.24   513876    30013.0   5.52
4       10.94   471514        NaN   1.12
...       ...      ...        ...    ...
3760   271.25       74        0.0   1.13
3761   102.50       74        0.0   1.33
3762      NaN       70        NaN    NaN
3763 -1625.00       35        NaN  14.32
3764    -7.07       34        NaN   1.53

[3765 rows x 11 columns]
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
선정된 우량주식100
         종목명      거래량  상장주식수      등락률     현재가      시가      고가    PER  시가총액  \
289     태광산업      298   1113   -0.17%  584000  589000  589000   1.97  6502
414      HDC    35519  59742   -1.58%    6240    6310    6370   6.78  3728
618     흥국화재    32033  64243   +0.83%    3040    3015    3090   0.82  1953
441   티와이홀딩스    31871  50429   -0.30%    6660    6680    6780   5.31  3359
759     대한화섬       26   1328   -0.39%  101500  100300  101800   4.64  1348
...      ...      ...    ...      ...     ...     ...     ...    ...   ...
690     삼영전자    58586  20000   -1.42%    8340    8410    8480  10.46  1668
693    노루홀딩스  1235577  13291  +10.27%   12240   11370   13250   6.19  1627
254     다우기술    19891  44867   +0.06%   18120   18030   18210   1.77  8130
2847      코텍    32710  15575   -1.60%    7400    7520    7540   4.57  1153
449     대한제강    45139  24647   +1.54%   13200   13000   13500   3.41  3253

          매출액   PBR  reciprocal_of_PBR
289   27039.0  0.12           8.333333
414   50449.0  0.13           7.692308
618   45289.0  0.14           7.142857
441    3536.0  0.16           6.250000
759    1509.0  0.16           6.250000
...       ...   ...                ...
690    2278.0  0.31           3.225806
693   10379.0  0.32           3.125000
254   92106.0  0.32           3.125000
2847   4286.0  0.32           3.125000
449   21416.0  0.32           3.125000

[100 rows x 12 columns]
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
우량주식 중 오르고 있는 주식 10개 선정
       종목명      거래량  상장주식수      등락률    현재가     시가     고가   PER  시가총액      매출액  \
693  노루홀딩스  1235577  13291  +10.27%  12240  11370  13250  6.19  1627  10379.0

      PBR  reciprocal_of_PBR  closing_price_percentage
693  0.32              3.125                  0.923774

In [14]:
import pandas as pd


class StockAnalyzer:
    def __init__(self,path):
        self.data = pd.read_excel(path)

    def preprocess_data(self):
        # Remove unnecessary columns
        remove = ['액면가', '거래대금', '외국인비율', '매수호가', '매도호가']
        df_cleaned = self.data.drop(columns=remove)
        
        # Convert all numbers to float
        for col in df_cleaned.columns:
            if col != '종목명' and df_cleaned[col].dtype == 'O': 
                df_cleaned[col] = df_cleaned[col].str.replace(',', '').str.replace('%', '').astype(float)
        
        # Drop NaN rows
        self.data = df_cleaned.dropna(subset=['시가총액', 'PER', 'PBR', '매출액'])

    def filter_stocks(self):
        return self.data[
            (self.data['시가총액'] >= 1000) &
            (self.data['매출액'] >= 1) &
            (self.data['PER'] >= 0) &
            (self.data['PBR'] <= 2)
        ]

    def get_top_stocks(self, stocks):
        stocks['PBR_inverse'] = 1 / stocks['PBR']
        return stocks.sort_values(by='PBR_inverse', ascending=False).head(100)

    def get_potential_stocks(self, stocks):
        potential_stocks = stocks[
            (stocks['거래량'] >= stocks['상장주식수'] * 10) &
            (stocks['등락률'] >= 0) &
            (stocks['현재가'] > stocks['시가'])
        ]
        potential_stocks['고가-현재가'] = (potential_stocks['고가'] - potential_stocks['현재가'])
        return potential_stocks.sort_values(by='고가-현재가').head(10)

    def analyze(self):
        self.preprocess_data()
        
        filtered_stocks = self.filter_stocks()
        top_stocks = self.get_top_stocks(filtered_stocks)
        
        print('------ 문제 2 ------')
        print(top_stocks['종목명'].tolist())
        
        potential_stocks = self.get_potential_stocks(top_stocks)
        
        print("------ 문제 3 ------")
        print(potential_stocks['종목명'].tolist())

# Run the analyzer
analyzer = StockAnalyzer('data/NaverFinance.xlsx')
analyzer.analyze()

------ 문제 2 ------
['태광산업', 'HDC', '흥국화재', '티와이홀딩스', '대한화섬', '현대지에프홀딩스', '한화생명', '이마트', '계룡건설', 'DB금융투자', '태영건설', '티케이케미칼', '세아홀딩스', '넥센', '한국가스공사', '한화손해보험', '교보증권', '세이브존I&C', '한솔홀딩스', '미래에셋생명', 'KPX홀딩스', '한진', 'SNT홀딩스', 'BGF', '한화', 'KCC건설', '동양생명', 'E1', 'DGB금융지주', '일신방직', '원익홀딩스', 'BNK금융지주', '한일홀딩스', 'HDC현대산업개발', '대한제분', 'KISCO홀딩스', '강남제비스코', '영풍', '동양', '삼천리', '서울가스', '골프존뉴딘홀딩스', '하림지주', '세방', '현대홈쇼핑', '화성산업', '코오롱', '서한', '피에이치에이', '유진기업', '현대차증권', '롯데지주', '현대제철', '한진중공업홀딩스', '대원산업', '한양증권', '부국증권', '기업은행', '농심홀딩스', 'DL건설', 'LF', '삼보판지', '한국앤컴퍼니', 'SK디스커버리', '서연', '신도리코', '한국철강', '예스코홀딩스', '케이씨', '동원개발', '우리금융지주', '이베스트투자증권', '신영증권', '경동도시가스', '휴스틸', '무학', '선광', '동일산업', 'DL이앤씨', 'GRT', '해성산업', '매일홀딩스', '삼양홀딩스', 'DRB동일', '아세아', 'GS', '광주신세계', '삼성생명', '한섬', '미창석유', '하나금융지주', '현대백화점', '고려제강', '무림P&P', '현대해상', '삼영전자', '노루홀딩스', '다우기술', '코텍', '대한제강']
------ 문제 3 ------
['노루홀딩스']

/var/folders/sb/2gzn9_qx589_ft0jp8q6nbbc0000gn/T/ipykernel_58554/2776393024.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stocks['PBR_inverse'] = 1 / stocks['PBR']
/var/folders/sb/2gzn9_qx589_ft0jp8q6nbbc0000gn/T/ipykernel_58554/2776393024.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  potential_stocks['고가-현재가'] = (potential_stocks['고가'] - potential_stocks['현재가'])