2023 06 29 2324i  
its dark outside. let get init

# 💼 HR Analytics: Job Change of Data Scientists

## Introduction

Welcome to this project! This notebook aims to explore, preprocess, and model the ["HR Analytics: Job Change of Data Scientists"](https://www.kaggle.com/datasets/arashnic/hr-analytics-job-change-of-data-scientists) dataset available on Kaggle. The dataset contains various features related to a person's job and demographic information, including education, city development, gender, and relevant experience. The target variable is whether the person is looking for a new job or not.

 We will go through the following steps in this 
Here's the markdown text explaining your existing code:

---

## 🚀 Loading Data

The first step in our project involves loading the necessary data files. We start by importing essential libraries such as `numpy` and `pandas`. Then we read the train and test CSV files. If running in a local environment, it tries to read local files, but if the code is running in a Kaggle environment, it reads files from the appropriate Kaggle directory.

## 💽 Concatenating DataFrames

To streamline our preprocessing, we concatenate the training and testing data into one DataFrame, `df`. This way, we ensure that any transformations applied to the data are consistent across both the training and testing sets. 

Additionally, we drop the `enrollee_id` column as it does not provide useful information for our predictive model. It's just an identifier for each enrollee.

## 🔢 Encoding Categorical Variables

Next, we use a `LabelEncoder` from the `sklearn` library to transform our categorical columns into numerical ones. Machine learning models require numerical inputs, so this step is crucial. Columns that we encode are 'city', 'gender', 'relevent_experience', 'enrolled_university', 'education_level', 'major_discipline', and 'company_type'.

## 🧮 Handling Special Cases

For columns like 'experience', 'company_size', and 'last_new_job', they contain special strings like '>20', '<1', etc., which cannot be handled directly by `LabelEncoder`. We define custom functions to transform these strings into representative numerical values. For example, in 'experience', we represent '>20' as 23 (assuming 23 years of experience for those with more than 20), '<1' as 0, and so on. Similarly, we handle the 'company_size' and 'last_new_job' columns.

## 🔀 Splitting DataFrames

Once our complete DataFrame is processed, we split it back into the training and testing sets using the original sizes of the training and test data.

## 🧠 Building the Model

We use the `QuadraticDiscriminantAnalysis` from the `sklearn` library to create our machine learning model. After training the model on the training data, we predict the target variable for the test data.

## 📤 Creating Submission File

Finally, we read the `sample_submission.csv` file and replace its 'target' column with our predictions, ready for submission.

---

Please modify the text above according to your needs.

# 💼 HR Analytics: 데이터 과학자의 직장 이동

## 소개

이 프로젝트에 오신 것을 환영합니다! 이 노트북에서는 Kaggle에서 제공하는 ["HR Analytics: 데이터 과학자의 직장 이동"](https://www.kaggle.com/datasets/arashnic/hr-analytics-job-change-of-data-scientists) 데이터셋을 탐색, 전처리, 모델링합니다. 이 데이터셋에는 사람의 직업과 인구통계 정보에 관한 다양한 특징이 포함되어 있습니다. 이 중 교육, 도시 개발, 성별, 그리고 관련 경험 등이 있습니다. 타겟 변수는 사람이 새로운 직장을 찾고 있는지 여부입니다.

이 프로젝트를 통해 우리는 다음의 단계들을 거쳐가게 됩니다:

---

## 🚀 데이터 로딩

프로젝트의 첫 단계는 필요한 데이터 파일들을 불러오는 것입니다. 우리는 먼저 `numpy`와 `pandas` 같은 필수 라이브러리들을 임포트합니다. 그 다음에는 학습과 테스트 CSV 파일들을 읽습니다. 로컬 환경에서 실행되면 로컬 파일을 읽으려 시도하지만, 만약 코드가 Kaggle 환경에서 실행되면 적절한 Kaggle 디렉토리에서 파일을 읽습니다.

## 💽 데이터프레임 합치기

전처리를 간편하게 하기 위해, 우리는 학습 데이터와 테스트 데이터를 하나의 데이터프레임, `df`로 합칩니다. 이렇게 하면 데이터에 적용되는 모든 변환들이 학습과 테스트 세트 양쪽에 일관되게 적용됩니다.

또한, 우리는 `enrollee_id` 열을 삭제합니다. 이는 각 참여자에 대한 식별자일 뿐이므로 우리의 예측 모델에 유용한 정보를 제공하지 않습니다.

## 🔢 범주형 변수 인코딩

다음으로, 우리는 `sklearn` 라이브러리의 `LabelEncoder`를 사용해 범주형 열들을 숫자형으로 변환합니다. 머신러닝 모델들은 숫자 입력을 요구하기 때문에 이 단계는 필수적입니다. 인코딩이 필요한 열들은 'city', 'gender', 'relevent_experience', 'enrolled_university', 'education_level', '

major_discipline', 그리고 'company_type'입니다.

## 🧮 특수 케이스 처리

'experience', 'company_size', 그리고 'last_new_job' 같은 열들은 '>20', '<1' 등과 같은 특수 문자열을 포함하고 있어, 이들은 `LabelEncoder`로 직접 처리할 수 없습니다. 우리는 이런 문자열들을 대표하는 숫자 값으로 변환하기 위해 사용자 정의 함수를 정의합니다. 예를 들어, 'experience'에서, 우리는 '>20'을 23으로 (20년 이상의 경험이 있는 사람들을 23년의 경험이 있다고 가정), '<1'을 0으로 표현하고, 이 외의 값들은 그대로 사용합니다. 'company_size'와 'last_new_job' 열도 비슷하게 처리합니다.

## 🔀 데이터프레임 분할

전체 데이터프레임이 처리되면, 우리는 원래의 학습 데이터와 테스트 데이터의 크기를 사용하여 데이터프레임을 다시 학습 세트와 테스트 세트로 분할합니다.

## 🧠 모델 생성

우리는 `sklearn` 라이브러리의 `QuadraticDiscriminantAnalysis`를 사용해 머신러닝 모델을 만듭니다. 학습 데이터로 모델을 훈련한 후에는 테스트 데이터에 대한 타겟 변수를 예측합니다.

## 📤 제출 파일 생성

마지막으로, `sample_submission.csv` 파일을 읽고 'target' 열을 우리의 예측 결과로 교체합니다. 이는 제출을 위한 준비 과정입니다.

---

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Load + analize the datset

In [2]:
import pandas as pd

try:
    traincsv = pd.read_csv('aug_train.csv')
except:
    traincsv = pd.read_csv('/kaggle/input/hr-analytics-job-change-of-data-scientists/aug_train.csv')
    print('wellcome to kaggle')

try:
    x_test = pd.read_csv('aug_test.csv')
except:
    x_test = pd.read_csv('/kaggle/input/hr-analytics-job-change-of-data-scientists/aug_test.csv')
#print(traincsv.head(3))
#print(testcsv)

### memo

so it looks like enrollee_id is irrelivent about the target(I will drop that).  
And also, since the city,gender,relevent_exp,enrolled_uni,education and manythings are str, I have to encode it to a number  
And we have to take care of NaN data  
And change never to 0 at last new job

In [3]:
#seperating the target
y_train = traincsv['target']
x_train = traincsv.drop(['target'], axis=1)
print(x_train.shape)
print(y_train.shape)

(19158, 13)
(19158,)

In [4]:
#print labels
import pandas as pd

# Extract the labels from the first row
labels = traincsv.columns

print(labels)

Index(['enrollee_id', 'city', 'city_development_index', 'gender',
       'relevent_experience', 'enrolled_university', 'education_level',
       'major_discipline', 'experience', 'company_size', 'company_type',
       'last_new_job', 'training_hours', 'target'],
      dtype='object')

## Data processing
0. make two csv into one (test,train)
1. remove enrollee id (irrelivent)
2. city to int
3. gender to int
4. rel exp to int
5. uni to int
6. education to int
7. exp modify
8. compy size modify
9. company type int
10. last new job modify

In [5]:
import pandas as pd


# Concatenate the two DataFrames along the row axis
df = pd.concat([x_train, x_test], ignore_index=True)
#remove enrollee id (since its irrelivent)
df = df.drop(['enrollee_id'], axis=1)
print(df.head(3))

       city  city_development_index gender      relevent_experience  \
0  city_103                   0.920   Male  Has relevent experience
1   city_40                   0.776   Male   No relevent experience
2   city_21                   0.624    NaN   No relevent experience

  enrolled_university education_level major_discipline experience  \
0       no_enrollment        Graduate             STEM        >20
1       no_enrollment        Graduate             STEM         15
2    Full time course        Graduate             STEM          5

  company_size company_type last_new_job  training_hours
0          NaN          NaN            1              36
1        50-99      Pvt Ltd           >4              47
2          NaN          NaN        never              83

## NAN replace (with most frequent)

In [6]:
# Check for NaN values in each label
nan_labels = df.columns[df.isna().any()].tolist()

print(nan_labels)

['gender', 'enrolled_university', 'education_level', 'major_discipline', 'experience', 'company_size', 'company_type', 'last_new_job']

In [7]:
columns_with_nan = ['gender', 'enrolled_university', 'education_level', 'major_discipline', 'experience', 'company_size', 'company_type', 'last_new_job']

for col in columns_with_nan:
    df[col].fillna(df[col].mode()[0], inplace=True)
print(df.head(3))

       city  city_development_index gender      relevent_experience  \
0  city_103                   0.920   Male  Has relevent experience
1   city_40                   0.776   Male   No relevent experience
2   city_21                   0.624   Male   No relevent experience

  enrolled_university education_level major_discipline experience  \
0       no_enrollment        Graduate             STEM        >20
1       no_enrollment        Graduate             STEM         15
2    Full time course        Graduate             STEM          5

  company_size company_type last_new_job  training_hours
0        50-99      Pvt Ltd            1              36
1        50-99      Pvt Ltd           >4              47
2        50-99      Pvt Ltd        never              83

In [8]:
# RE Check for NaN values in each label
nan_labels = df.columns[df.isna().any()].tolist()

print(nan_labels)

[]

## Encoding to int

In [9]:
#str to int
from sklearn.preprocessing import LabelEncoder

# Initialize a LabelEncoder
le = LabelEncoder()

# List of columns to encode
cols_to_encode = ['city', 'gender', 'relevent_experience', 'enrolled_university', 
                    'education_level', 'major_discipline', 'company_type']

# Iterate over each categorical column and transform it
for col in cols_to_encode:
    df[col] = le.fit_transform(df[col])
    
print(df.head(3))

   city  city_development_index  gender  relevent_experience  \
0     5                   0.920       1                    0
1    77                   0.776       1                    1
2    64                   0.624       1                    1

   enrolled_university  education_level  major_discipline experience  \
0                    2                0                 5        >20
1                    2                0                 5         15
2                    0                0                 5          5

  company_size  company_type last_new_job  training_hours
0        50-99             5            1              36
1        50-99             5           >4              47
2        50-99             5        never              83

## Encoding 2

In [10]:
cols_to_handle = ['experience', 'company_size', 'last_new_job']

for col in cols_to_handle:
    print(f"Unique values for {col}: {df[col].unique()}")

Unique values for experience: ['>20' '15' '5' '<1' '11' '13' '7' '17' '2' '16' '1' '4' '10' '14' '18'
 '19' '12' '3' '6' '9' '8' '20']
Unique values for company_size: ['50-99' '<10' '10000+' '5000-9999' '1000-4999' '10/49' '100-500'
 '500-999']
Unique values for last_new_job: ['1' '>4' 'never' '4' '3' '2']

In [11]:
def handle_experience(x):
    if pd.isnull(x):
        return x  # or define a default value
    elif x == '>20':
        return 23
    elif x == '<1':
        return 0
    else:
        return int(x)

def handle_company_size(x):
    if pd.isnull(x):
        return x  # or define a default value
    elif x == '<10':
        return 5
    elif x == '10/49':
        return 30
    elif x == '50-99':
        return 75
    elif x == '100-500':
        return 300
    elif x == '500-999':
        return 750
    elif x == '1000-4999':
        return 3000
    elif x == '5000-9999':
        return 7500
    elif x == '10000+':
        return 15000

def handle_last_new_job(x):
    if pd.isnull(x):
        return x  # or define a default value
    elif x == 'never':
        return 0
    elif x == '>4':
        return 5
    else:
        return int(x)

# Applying the transformations
df['experience'] = df['experience'].map(handle_experience)
df['company_size'] = df['company_size'].map(handle_company_size)
df['last_new_job'] = df['last_new_job'].map(handle_last_new_job)

print(df.head(3))

   city  city_development_index  gender  relevent_experience  \
0     5                   0.920       1                    0
1    77                   0.776       1                    1
2    64                   0.624       1                    1

   enrolled_university  education_level  major_discipline  experience  \
0                    2                0                 5          23
1                    2                0                 5          15
2                    0                0                 5           5

   company_size  company_type  last_new_job  training_hours
0            75             5             1              36
1            75             5             5              47
2            75             5             0              83

## Back to train, test

In [12]:
import pandas as pd

# Split the concatenated DataFrame back into x_train and x_test
x_train = df.loc[:len(x_train)-1, :]
x_test = df.loc[len(x_train):, :]

# Reset the index for each DataFrame
x_train.reset_index(drop=True, inplace=True)
x_test.reset_index(drop=True, inplace=True)

## valdation test / check acc

In [13]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Split the original training data into training and validation set
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.2, random_state=42)

clf = QuadraticDiscriminantAnalysis()
clf.fit(x_train,y_train)

# Predict on validation data
y_val_pred = clf.predict(x_val)

# Print the accuracy score
print("Accuracy on validation data: %.4f "%accuracy_score(y_val, y_val_pred))

Accuracy on validation data: 0.7523

In [14]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

clf = QuadraticDiscriminantAnalysis()
clf.fit(x_train,y_train)

y_test = clf.predict(x_test)

In [15]:
try:
    submit = pd.read_csv("sample_submission.csv")
except:
    submit = pd.read_csv("/kaggle/input/hr-analytics-job-change-of-data-scientists/sample_submission.csv")
submit.info

<bound method DataFrame.info of       Unnamed: 0.4  Unnamed: 0.3  Unnamed: 0.2  Unnamed: 0.1  Unnamed: 0  \
0                0             0             0             0           0
1                1             1             1             1           1
2                2             2             2             2           2
3                3             3             3             3           3
4                4             4             4             4           4
...            ...           ...           ...           ...         ...
2124          2124          2124          2124          2124        2124
2125          2125          2125          2125          2125        2125
2126          2126          2126          2126          2126        2126
2127          2127          2127          2127          2127        2127
2128          2128          2128          2128          2128        2128

      enrollee_id  target
0           32403       0
1            9858       0
2           31806       1
3           27385       0
4           27724       0
...           ...     ...
2124         1289       0
2125          195       0
2126        31762       0
2127         7873       1
2128        12215       0

[2129 rows x 7 columns]>

In [16]:
submit['target'] = y_test.astype('int64')
try:
    submit.to_csv("/kaggle/working/sample_submission.csv")
except:
    submit.to_csv("sample_submission.csv")